### ISSUE TITLE
Import Dorothea interactions not working

### ISSUE THREAD

**Issue by smuellerd** [saezlab/OmnipathR#62]
Hi @deeenes,

I am currently having trouble loading the Dorothea interactions from OmnipathR: 
`OmnipathR::import_dorothea_interactions(dorothea_levels = c("A", "B", "C"))`

I get the following error
```
Error in `mutate()`:
ℹ In argument: `n_references = ifelse(...)`.
Caused by error in `map()`:
ℹ In index: 1.
Caused by error in `.f()`:
! Arguments in `...` must be passed by position, not name.
✖ Problematic argument:
• outsep = outsep
Run `rlang::last_error()` to see where the error occurred. 
```

I was using the bioconductor OmnipathR package and then re-tried with the current github version but got the same error.

Thanks for your help in advance!

**Comment by deeenes** [comment]
Hi Sophia, This is the same as #56 and #57, and should've been already fixed in `master`.

**Comment by smuellerd** [comment]
Hi Denes, but why do I still get the error after I download the current github version.  
`devtools::install_github('saezlab/OmnipathR')`

**Comment by smuellerd** [comment]
I just restarted everything and now it works! Thanks for your help.
