### ISSUE TITLE
get_collectri() and OmnipathR download not working 

### ISSUE THREAD

**Issue by nvokes** [saezlab/OmnipathR#84]
I have been following the decoupleR vignette and have been unable to run get_collectri(). After reading through the issue on the decoupleR page, I downladed the latest version of decoupleR (2.5.3). When I try to run remotes::install_github('saezlab/OmnipathR') to also update OmnipathR, I get the following error: 
Error: package or namespace load failed for ‘OmnipathR’ in namespaceExport(ns, exports):
 undefined exports: cookie 

So I went to the github and manually downloaded and installed OmnipathR 3.9.3. However, when I then tried get_collectri(), I receive the following set of errors: 

[2023-09-12 15:00:20] [SUCCESS] [OmnipathR] Downloaded 64958 interactions.
Error in `mutate()`:
ℹ In argument: `across(columns, ~filter_evs_lst(.x, datasets, resources, columns))`.
Caused by error in `across()`:
! Can't compute column `undirected`.
Caused by error in `map()`:
ℹ In index: 1.
Caused by error in `keep()`:
ℹ In index: 1.
Caused by error in `ev$dataset`:
! $ operator is invalid for atomic vectors
Run `rlang::last_trace()` to see where the error occurred.
Warning message:
In decoupleR::get_collectri(organism = "human", split_complexes = FALSE) :
  The installed version of OmnipathR is older than 3.9.4 To make
    sure CollecTRI and DoRothEA data is processed correctly, please update to
    the latest version by `remotes::install_github('https://github.com/saezlab/omnipath.git')`

Is there a downloadable OmnipathR v3.9.4?

**Comment by deeenes** [comment]
Thanks for reporting this! I forgot to add `R/cookie.R` to git tracking, I've just fixed it in 73dca2e

If you do again `remotes::install_github('saezlab/OmnipathR')`, it should work

**Comment by nvokes** [comment]
Thank you! I was able to download the latest version (3.9.7) so that took care of that! 

It looks like I'm still getting the same error in calling the function though: 

[2023-09-12 15:40:04] [SUCCESS] [OmnipathR] Downloaded 64958 interactions.
Error in `mutate()`:
ℹ In argument: `across(columns, ~filter_evs_lst(.x, datasets, resources, columns))`.
Caused by error in `across()`:
! Can't compute column `undirected`.
Caused by error in `map()`:
ℹ In index: 1.
Caused by error in `keep()`:
ℹ In index: 1.
Caused by error in `ev$dataset`:
! $ operator is invalid for atomic vectors
Run `rlang::last_trace()` to see where the error occurred.

**Comment by deeenes** [comment]
I can not reproduce this second issue. The reason might be another old package, best to make sure all packages, especially `purrr` and the other `tidyverse` ones, are up to date. If the issue still persists, you can try with an empty cache:

```
library(OmnipathR)
omnipath_set_cachedir('tmpcache')
ci <- collectri()

unlink('tmpcache', recursive = TRUE)
```

If it still fails, please show me here a log trace:

```
library(OmnipathR)
omnipath_set_cachedir('tmpcache')
omnipath_set_console_loglevel('trace')
ci <- collectri()
```

**Comment by nvokes** [comment]
Updated the packages and that worked. Thanks so much for the help!
