### ISSUE TITLE
Error: Error installing package 'OmnipathR': when trying to install LianaR

### ISSUE THREAD

**Issue by maximelepetit** [saezlab/OmnipathR#94]
Hi,
I'm having an issue with OmnipathR when i try to install liana R wrapper :+1: 

```
renv::install("saezlab/liana")
# Downloading packages -------------------------------------------------------
- Downloading liana from GitHub ...             OK [6.9 Mb in 0.73s]
- Downloading OmnipathR from GitHub ...         OK [6.9 Mb in 0.9s]
- Downloading basilisk.utils from GitHub ...    OK [32.9 Kb in 0.63s]
- Downloading basilisk from GitHub ...          OK [48.9 Kb in 0.48s]
Successfully downloaded 4 packages in 12 seconds.

The following package(s) will be installed:
- basilisk       [LTLA/basilisk]
- basilisk.utils [LTLA/basilisk.utils]
- liana          [saezlab/liana]
- OmnipathR      [saezlab/OmnipathR]
These packages will be installed into "~/Projects/liana/renv/library/R-4.2/x86_64-pc-linux-gnu".

Do you want to proceed? [Y/n]: Y

# Installing packages --------------------------------------------------------
- Installing OmnipathR ...                      FAILED
Error: Error installing package 'OmnipathR':
=====================================

Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
* installing *source* package ‘OmnipathR’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘metaboliteIDmapping’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘OmnipathR’
* removing ‘/home/labex-cortex/Projects/liana/renv/library/R-4.2/x86_64-pc-linux-gnu/.renv/1/OmnipathR’
install of package 'OmnipathR' failed [error code 1]
Traceback (most recent calls last):
12: renv::install("saezlab/liana")
11: renv_install_impl(records)
10: renv_install_staged(records)
 9: renv_install_default(records)
 8: handler(package, renv_install_package(record))
 7: renv_install_package(record)
 6: withCallingHandlers(renv_install_package_impl(record), error = function(e) writef("FAILED"))
 5: renv_install_package_impl(record)
 4: r_cmd_install(package, path) 
 3: r_exec_error(package, output, "install", status)
 2: abort(all)
 1: stop(fallback)
```
This error also appear when i manually install OmnipathR from Github:

```
renv::install("saezlab/OmnipathR")
# Downloading packages -------------------------------------------------------
- Downloading OmnipathR from GitHub ...         OK [6.9 Mb in 0.95s]
Successfully downloaded 1 package in 1.8 seconds.

The following package(s) will be installed:
- OmnipathR [saezlab/OmnipathR]
These packages will be installed into "~/Projects/liana/renv/library/R-4.2/x86_64-pc-linux-gnu".

Do you want to proceed? [Y/n]: Y

# Installing packages --------------------------------------------------------
- Installing OmnipathR ...                      FAILED
Error: Error installing package 'OmnipathR':
=====================================

Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
* installing *source* package ‘OmnipathR’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘metaboliteIDmapping’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘OmnipathR’
* removing ‘/home/labex-cortex/Projects/liana/renv/library/R-4.2/x86_64-pc-linux-gnu/.renv/1/OmnipathR’
install of package 'OmnipathR' failed [error code 1]
Traceback (most recent calls last):
12: renv::install("saezlab/OmnipathR")
11: renv_install_impl(records)
10: renv_install_staged(records)
 9: renv_install_default(records)
 8: handler(package, renv_install_package(record))
 7: renv_install_package(record)
 6: withCallingHandlers(renv_install_package_impl(record), error = function(e) writef("FAILED"))
 5: renv_install_package_impl(record)
 4: r_cmd_install(package, path)
 3: r_exec_error(package, output, "install", status)
 2: abort(all)
 1: stop(fallback)
```

I try to install manually metaboliteIDmapping and i have also an error : 

```
renv::install("Bioc::metaboliteIDmapping")
# Downloading packages -------------------------------------------------------
- Downloading metaboliteIDmapping from BioCann ... OK [file is up to date]
Successfully downloaded 1 package in 1.6 seconds.

The following package(s) will be installed:
- AnnotationDbi          [1.60.2]
- AnnotationHub          [3.6.0]
- BiocFileCache          [2.6.1]
- Biostrings             [2.66.0]
- blob                   [1.2.4]
- DBI                    [1.2.1]
- dbplyr                 [2.4.0]
- DT                     [0.31]
- interactiveDisplayBase [1.36.0]
- KEGGREST               [1.38.0]
- metaboliteIDmapping    [1.0.0]
- plogr                  [0.2.0]
- RSQLite                [2.3.4]
These packages will be installed into "~/Projects/liana/renv/library/R-4.2/x86_64-pc-linux-gnu".

Do you want to proceed? [Y/n]: Y

# Installing packages --------------------------------------------------------
- Installing blob ...                           OK [linked from cache]
- Installing DBI ...                            OK [linked from cache]
- Installing dbplyr ...                         OK [linked from cache]
- Installing plogr ...                          OK [linked from cache]
- Installing RSQLite ...                        OK [linked from cache]
- Installing BiocFileCache ...                  OK [linked from cache]
- Installing Biostrings ...                     OK [linked from cache]
- Installing KEGGREST ...                       OK [linked from cache]
- Installing AnnotationDbi ...                  OK [linked from cache]
- Installing DT ...                             OK [linked from cache]
- Installing interactiveDisplayBase ...         OK [linked from cache]
- Installing AnnotationHub ...                  OK [linked from cache]
- Installing metaboliteIDmapping ...            FAILED
Error: Error installing package 'metaboliteIDmapping':
===============================================

* installing *source* package ‘metaboliteIDmapping’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘metaboliteIDmapping’:
 .onLoad failed in loadNamespace() for 'metaboliteIDmapping', details:
  call: collect(., Inf)
  error: Failed to collect lazy table.
Caused by error in `db_collect()`:
! Arguments in `...` must be used.
✖ Problematic argument:
• ..1 = Inf
ℹ Did you misspell an argument name?
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/labex-cortex/Projects/liana/renv/library/R-4.2/x86_64-pc-linux-gnu/.renv/1/metaboliteIDmapping’
install of package 'metaboliteIDmapping' failed [error code 1]
Traceback (most recent calls last):
12: renv::install("Bioc::metaboliteIDmapping")
11: renv_install_impl(records)
10: renv_install_staged(records)
 9: renv_install_default(records)
 8: handler(package, renv_install_package(record))
 7: renv_install_package(record)
 6: withCallingHandlers(renv_install_package_impl(record), error = function(e) writef("FAILED"))
 5: renv_install_package_impl(record)
 4: r_cmd_install(package, path)
 3: r_exec_error(package, output, "install", status)
 2: abort(all)
 1: stop(fallback)
```
Best regards 

Maxime

**Comment by maximelepetit** [comment]
My session Info : 
```
sessionInfo()
R version 4.2.3 (2023-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] gitcreds_0.1.2      crayon_1.5.2        withr_2.5.2         lifecycle_1.0.4     magrittr_2.0.3      rlang_1.1.3         cli_3.6.2           renv_1.0.3          curl_5.2.0         
[10] remotes_2.4.2.1     rstudioapi_0.15.0   fs_1.6.3            vctrs_0.6.5         tools_4.2.3         glue_1.7.0          purrr_1.0.2         compiler_4.2.3      BiocManager_1.30.22
[19] usethis_2.2.2      
```

**Comment by deeenes** [comment]
Hi Maxime,

I'm about to fix this right now, until then a few commits older version should work:

```
library(remotes)
remotes::install_github('saezlab/OmnipathR', ref = '4b83e3c')
```

Apologies for the inconvenience.

Best,

Denes

**Comment by enblacar** [comment]
Hi @deeenes,

Thank you for the work towards fixing the error! 

What is the current status of the hotfix implementation? My R package is failing in all CI tests due to Omnipath not being installed correctly.

Best,
Enrique

**Comment by vkartha** [comment]
Same issue here, just following up that I can't install LianaR due to this OmnipathR dependency installation failure

**Comment by deeenes** [comment]
@enblacar Many thanks for the reminders, somehow I thought this has been fixed already. But indeed, `metaboliteIDMapping` was listed as a suggested dependency. Let me know if it works now? Because I'm not 100% sure this was the reason.

Hello @vkartha, Interesting, with which versions of `tidyr` you do vs. do not see the error?

**Comment by enblacar** [comment]
Hi @deeenes,

Unfortunately, it still fails during CI in GitHub. I attach the error log:

```
 ✖ Failed to build OmnipathR 3.13.5 (462ms)
  Error: 
  ! error in pak subprocess
  Caused by error in `stop_task_build(state, worker)`:
  ! Failed to build source package OmnipathR.
  ---
  Backtrace:
  1. pak::lockfile_install(".github/pkg.lock")
  2. pak:::remote(function(...) { …
  3. err$throw(res$error)
  ---
  Subprocess backtrace:
   1. base::withCallingHandlers(cli_message = function(msg) { …
   2. get("lockfile_install_internal", asNamespace("pak"))(...)
   3. plan$install()
   4. pkgdepends::install_package_plan(plan, lib = private$library, num_workers = nw, …
   5. base::withCallingHandlers({ …
   6. pkgdepends:::handle_events(state, events)
   7. pkgdepends:::handle_event(state, i)
   8. pkgdepends:::stop_task(state, worker)
   9. pkgdepends:::stop_task_build(state, worker)
  10. base::throw(pkg_error("Failed to build source package {.pkg {pkg}}.", …
  11. | base::signalCondition(cond)
  12. global (function (e) …
  Execution halted
  Error: Process completed with exit code 1.
```

Fingers crossed we find the error causing this soon!
Enrique

**Comment by deeenes** [comment]
@enblacar - And you too don't see the trace from the actual error, do you?

**Comment by enblacar** [comment]
Hi @deeenes,

Not really... I wish I could be more helpful with the errors logs. Maybe unrelated, but I get a different log depending on the platforms.

This is for ubuntu, in which the error seems related to Matrix and Seurat:

```
Dependency resolution
  Warning message:
  package ‘pak’ was built under R version 4.2.3 
  ℹ Creating lockfile '.github/pkg.lock'
  
  ✔ Updated metadata database: 5.07 MB in 10 files.
  
  ℹ Creating lockfile '.github/pkg.lock'
  ℹ Updating metadata database
  ✔ Updating metadata database ... done
  
  ℹ Creating lockfile '.github/pkg.lock'
  ✖ Creating lockfile '.github/pkg.lock' [12.1s]
  
  Error: 
  ! error in pak subprocess
  Caused by error: 
  ! Could not solve package dependencies:
  * deps::.:
    * Can't install dependency Seurat
    * Can't install dependency SeuratObject
  * Seurat: Can't install dependency Matrix (>= 1.5-0)
  * Matrix: Needs R >= 4.5
  * Matrix: Needs R >= 4.4.0
  * SeuratObject: Can't install dependency Matrix (>= 1.6.4)
  * any::sessioninfo: dependency conflict
  * any::rcmdcheck: dependency conflict
  ---
  Backtrace:
  1. pak::lockfile_create(c(deps, extra_deps), lockfile = ".github/pkg.lock", …
  2. pak:::remote(function(...) { …
  3. err$throw(res$error)
  ---
  Subprocess backtrace:
  1. base::withCallingHandlers(cli_message = function(msg) { …
  2. get("lockfile_create_internal", asNamespace("pak"))(...)
  3. prop$stop_for_solution_error()
  4. private$plan$stop_for_solve_error()
  5. pkgdepends:::pkgplan_stop_for_solve_error(self, private)
  6. base::throw(new_error("Could not solve package dependencies:\n", msg, …
  7. | base::signalCondition(cond)
  8. global (function (e) …
  Execution halted
  Error: Process completed with exit code 1.
```

This is for windows, in which it points to liana:

```
Dependency resolution
  ℹ Creating lockfile '.github/pkg.lock'
  
  ✔ Updated metadata database: 7.55 MB in 17 files.
  
  ℹ Creating lockfile '.github/pkg.lock'
  ℹ Updating metadata database
  ✔ Updating metadata database ... done
  
  ℹ Creating lockfile '.github/pkg.lock'
  ✖ Creating lockfile '.github/pkg.lock' [24.7s]
  
  Error: 
  ! error in pak subprocess
  Caused by error: 
  ! Could not solve package dependencies:
  * deps::.: Can't install dependency saezlab/liana (>= 0.1.6)
  * saezlab/liana:
    * Can't install dependency LTLA/basilisk.utils
    * Can't install dependency LTLA/basilisk
  * LTLA/basilisk.utils: ! pkgdepends resolution error for LTLA/basilisk.utils.
  Caused by error: 
  ! Cannot query GitHub, are you offline?
  * LTLA/basilisk: ! pkgdepends resolution error for LTLA/basilisk.
  Caused by error: 
  ! Cannot query GitHub, are you offline?
  * any::sessioninfo: dependency conflict
  * any::rcmdcheck: dependency conflict
  ---
  Backtrace:
  1. pak::lockfile_create(c(deps, extra_deps), lockfile = ".github/pkg.lock", …
  2. pak:::remote(function(...) { …
  3. err$throw(res$error)
  ---
  Subprocess backtrace:
  1. base::withCallingHandlers(cli_message = function(msg) { …
  2. get("lockfile_create_internal", asNamespace("pak"))(...)
  3. prop$stop_for_solution_error()
  4. private$plan$stop_for_solve_error()
  5. pkgdepends:::pkgplan_stop_for_solve_error(self, private)
  6. base::throw(new_error("Could not solve package dependencies:\n", msg, …
  7. | base::signalCondition(cond)
  8. global (function (e) …
  Execution halted
  Error: Process completed with exit code 1.
```

And this is for mac, the one that actually points to Omnipath:

```
  ℹ Packaging OmnipathR 3.13.5
  ✔ Packaged OmnipathR 3.13.5 (1s)
  ℹ Building OmnipathR 3.13.5
  ✖ Failed to build OmnipathR 3.13.5 (473ms)
  Error: 
  ! error in pak subprocess
  Caused by error in `stop_task_build(state, worker)`:
  ! Failed to build source package OmnipathR.
  ---
  Backtrace:
  1. pak::lockfile_install(".github/pkg.lock")
  2. pak:::remote(function(...) { …
  3. err$throw(res$error)
  ---
  Subprocess backtrace:
   1. base::withCallingHandlers(cli_message = function(msg) { …
   2. get("lockfile_install_internal", asNamespace("pak"))(...)
   3. plan$install()
   4. pkgdepends::install_package_plan(plan, lib = private$library, num_workers = nw, …
   5. base::withCallingHandlers({ …
   6. pkgdepends:::handle_events(state, events)
   7. pkgdepends:::handle_event(state, i)
   8. pkgdepends:::stop_task(state, worker)
   9. pkgdepends:::stop_task_build(state, worker)
  10. base::throw(pkg_error("Failed to build source package {.pkg {pkg}}.", …
  11. | base::signalCondition(cond)
  12. global (function (e) …
  Execution halted
  Error: Process completed with exit code 1.
```

Perhaps are all of them related? At least between liana-basilisk-omnipath? Perhaps there is a connexion to the version of Matrix and Seurat? 

I hope this helps!
Enrique

**Comment by deeenes** [comment]
Hi Enrique @enblacar,

I think I've just [fixed this issue](https://github.com/saezlab/OmnipathR/actions/runs/10378227461/job/28734043250). `pak` hides errors from package builds, so I created a github action where I first installed by `remotes::install_github`, then fixed all the errors that popped up, and finally checked if `pak` also runs without error. One thing though that you need for success in the ubuntu environment is to install the `libglpk40` package: it is required by `igraph`. See [this part](https://github.com/saezlab/OmnipathR/actions/runs/10378227461/workflow#L33) of the action.

**Comment by Yafei-Wang** [comment]
Hi, I am trying to to install OmnipathR with: install_github('saezlab/OmnipathR')
The error shows as below
Error in parse(outFile) : 
     /tmp/RtmpaOrTqZ/Rbuild129cd7f784855/OmnipathR/R/hmdb.R:159:13: unexpected input
   158:             fields,
   159:             \
                    ^
   ERROR: unable to collate and parse R files for package ‘OmnipathR’
─  removing ‘/tmp/RtmpaOrTqZ/Rinst129cd15e92f66/OmnipathR’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'OmnipathR' from GitHub:
  ! System command 'R' failed

**Comment by deeenes** [comment]
Hi @Yafei-Wang, Next time please open a new issue, this is an old one which is only waiting for a follow up feedback.

Can you please share some more details how do you call `install_github` exactly, and in what kind of environment (OS, R version)? For me this runs successfully:

```
library(remotes)
install_github('saezlab/OmnipathR')
```

The output:

```
R version 4.4.1 (2024-06-14) -- "Race for Your Life"
Platform: x86_64-pc-linux-gnu (64-bit)
[ins] r$> library(remotes)
[ins] r$> install_github('saezlab/OmnipathR')
Downloading GitHub repo saezlab/OmnipathR@HEAD

── R CMD build ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/tmp/Rtmph0Spa1/remotes6e97c3374e84c/saezlab-OmnipathR-d707d6d/DESCRIPTION’ ...
─  preparing ‘OmnipathR’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts (428ms)
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘OmnipathR_3.13.17.tar.gz’
   
Installing package into ‘/home/denes/R/x86_64-pc-linux-gnu-library/4.4’
(as ‘lib’ is unspecified)
* installing *source* package ‘OmnipathR’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (OmnipathR)
[ins] r$>
```

**Comment by Yafei-Wang** [comment]
Hi @deeenes, Thank you for your quick response! Sorry that it is my first time to post question in github, not that familiar with the rules. 

My R version is 4.0.3 (unfortunately, I am not able to update it). I tried to install OmnipathR through Bioconductor with the command "BiocManager::install("OmnipathR" )", it seems works, but the OmnipathR version is only 2.0.0, and I can not process the analysis for decoupleR(I need OmnipathR 3.11.10 according to the tutorials). Then I tried to install it from github with the command: install_github('saezlab/OmnipathR'), but it shows the error as I posted above: (

**Comment by deeenes** [comment]
@Yafei-Wang R 4.0.0 is indeed very old. The reason of the error is the backslash [anonymous function syntax introduced in R 4.1.0](https://www.jumpingrivers.com/blog/new-features-r410-pipe-anonymous-functions/):

```
... %>% map(\(x) {...})
```

Now I [replaced it](https://github.com/saezlab/OmnipathR/commit/8e15694d00561e603264344cf7b460e3a296fed6) with the traditional syntax, should be working now in the old R.

**Comment by Yafei-Wang** [comment]
> @Yafei-Wang R 4.0.0 is indeed very old. The reason of the error is the backslash [anonymous function syntax introduced in R 4.1.0](https://www.jumpingrivers.com/blog/new-features-r410-pipe-anonymous-functions/):
> 
> ```
> ... %>% map(\(x) {...})
> ```
> 
> Now I [replaced it](https://github.com/saezlab/OmnipathR/commit/8e15694d00561e603264344cf7b460e3a296fed6) with the traditional syntax, should be working now in the old R.

Thank you so much!!

**Comment by enblacar** [comment]
Hi @deeenes,

The CI tests seem to go through now! Thanks for the work on this fix!

Enrique
